"""
Sync the Legal Codex from the sibling L-Lawliet project.

L-Lawliet is the single source of truth for statute data (PRD §3). This script:
  1. Copies L-Lawliet/api/index.py -> api/index.py   (the FastAPI backend, unchanged)
  2. Extracts LAWS_DATABASE from it -> data/codex-cache.js  (offline fallback, PRD §9)

Never hand-edit api/index.py or data/codex-cache.js here. Edit L-Lawliet, then run:

    python scripts/sync_codex.py [path-to-L-Lawliet]

Default path: ../L-Lawliet (relative to this repo's root).
"""
import ast
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else ROOT.parent / "L-Lawliet"
SRC_API = SOURCE / "api" / "index.py"

# Defaults the Pydantic Law model fills in when a field is omitted
FIELD_DEFAULTS = {"status": "Active", "user_notes": []}


def extract_laws(py_source: str) -> list:
    """Find the `LAWS_DATABASE = [...]` literal and evaluate it safely (no import of FastAPI)."""
    tree = ast.parse(py_source)
    for node in tree.body:
        if (
            isinstance(node, ast.Assign)
            and any(isinstance(t, ast.Name) and t.id == "LAWS_DATABASE" for t in node.targets)
            and isinstance(node.value, ast.List)
        ):
            return ast.literal_eval(node.value)
    raise SystemExit("LAWS_DATABASE literal not found in " + str(SRC_API))


def main():
    if not SRC_API.exists():
        raise SystemExit(f"Cannot find {SRC_API}. Pass the L-Lawliet path as an argument.")

    source_text = SRC_API.read_text(encoding="utf-8")
    laws = [{**FIELD_DEFAULTS, **law} for law in extract_laws(source_text)]

    api_dir = ROOT / "api"
    api_dir.mkdir(exist_ok=True)
    shutil.copyfile(SRC_API, api_dir / "index.py")

    data_dir = ROOT / "data"
    data_dir.mkdir(exist_ok=True)
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    payload = json.dumps({"count": len(laws), "laws": laws}, ensure_ascii=False, indent=2)
    (data_dir / "codex-cache.js").write_text(
        "// AUTO-GENERATED by scripts/sync_codex.py from L-Lawliet/api/index.py. Do not edit.\n"
        f"// Synced: {stamp}\n"
        "// Offline fallback for JurisAPI when /api/v1 is unreachable (PRD §9).\n"
        f"window.JURIS_CODEX_CACHE = {payload};\n",
        encoding="utf-8",
    )
    print(f"Synced {len(laws)} laws from {SOURCE.name} -> api/index.py, data/codex-cache.js")


if __name__ == "__main__":
    main()
